name: Validate integration

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    name: HACS
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: HACS validation
        uses: docker://ghcr.io/hacs/action@sha256:3b5eaf821de267ede11dfdd3a792679dfdc72f52bdaf395422b39f0cfad27120
        env:
          INPUT_CATEGORY: integration
          INPUT_COMMENT: "false"
          INPUT_GITHUB_TOKEN: ${{ github.token }}
          INPUT_IGNORE: brands
          INPUT_REPOSITORY: ${{ github.repository }}

  validate-hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Hassfest validation
        run: >-
          docker run --rm
          --volume "${GITHUB_WORKSPACE}:/github/workspace"
          ghcr.io/home-assistant/hassfest@sha256:5fc3c5d7df109d248a61acfb0a675b38b1e4dc3a202feb260a8e33696f9803e3
